spring:
  application:
    name: redis-cache-demo
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/redis-cache-db
    username: chainmeans
    password: chainmeans
  data:
    jdbc:
      dialect: mysql
    redis:
      port: 16379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
  cache:
    type: redis
    cache-names:
      - person
      - allPersons